CC=gcc
CFLAGS= -Wall -g 

.PHONY: default
default: mdb-lookup-server-nc-2 mdb-lookup-server-nc-1

mdb-lookup-server-nc-2: 

mdb-lokup-server-nc-1: 

.PHONY: clean
clean: 
	rm -f *.o *~

.PHONY: all
all: clean default


